import type { ReactNode } from "react";

// One definition per recurring term, so every "?" on every page explains it the same way.
// Wording rule: findings are flags for examiner review, never proof.
export const GLOSSARY: Record<string, { title: string; text: ReactNode }> = {
  fdr: { title: "False-alarm budget (FDR)", text: "The false discovery rate: the share of statistical flags allowed to be false alarms. At 10%, out of 20 statistical flags about 2 at most are expected to be wrong. Documented facts are listed on their own basis and do not use this budget." },
  fdrChecked: { title: "Is the budget honest?", text: "Checked on 40 independently seeded panels where every entity is healthy, so any flag there is a false alarm. The realised rate stays at or below the promise. See Validation." },
  qvalue: { title: "q-value", text: "The entity's combined evidence after correcting for testing every entity at once (Benjamini-Hochberg). An entity is flagged when q is at or below the budget. Smaller means stronger evidence." },
  pvalue: { title: "p-value", text: "How surprising this pattern would be if the entity behaved like its peers. Small values mean chance is an unlikely explanation. Calibrated on all-healthy panels, so p = 0.05 really means 1 in 20." },
  attention: { title: "Supervisory attention", text: "A 0 to 100 score that orders the queue: the larger of 20 × −log10(q) and the severity of any documented fact. It ranks where to look first; it is not a grade of the SOC." },
  basis: { title: "Flag basis", text: <>Amber <b>FDR-flagged</b>: calibrated statistics, counted in the false-alarm budget. Red <b>documented fact</b>: a deterministic finding such as a blind tactic, a retention gap or a missed red-team technique.</> },
  strongest: { title: "Strongest evidence", text: "The finding with the smallest p-value (or highest severity) for this entity, with its effect against peers. Hover “+n more” for the rest." },
  trend: { title: "12-month trend", text: "Monthly mean model score for likely-superficial case handling. A rising line means more cases each month look closed without real investigation." },
  execGap: { title: "Execution gap", text: "Practice that looks fine on paper but not in the records: cases closed implausibly fast, templated notes, skipped investigation steps, closures bunched under the SLA." },
  negSpace: { title: "Negative space", text: "Evidence that should exist and is missing: critical assets gone silent, tactics the SOC cannot see, detection rules that stopped firing, records not retained." },
  findings: { title: "Findings", text: "Each detector that fired for an entity. A finding states the evidence, the peer comparison, the records behind it and the obligation it tests. It is a flag for examiner review." },
  blind: { title: "Blind", text: "None of the entity's declared log sources can support detecting this ATT&CK tactic, so no alerts there means blind, not safe. A documented fact, not a statistic." },
  quiet: { title: "Quiet", text: "The entity could see this tactic but raised far fewer alerts than its asset mix and peers predict. Worth asking why." },
  tactic: { title: "ATT&CK tactic", text: "A stage of an attack in the MITRE ATT&CK framework, such as Initial Access or Lateral Movement. A SOC should be able to see every tactic that applies to its assets." },
  providerEffect: { title: "Provider effect", text: "The shift in clients' likely-superficial rate that a random-effects model attributes to the SOC provider itself, against every other SOC, in percentage points (pp). Ordinary entity-to-entity variation is separated out." },
  ci90: { title: "90% interval", text: "The range that would contain the true value in 90% of repeats. An interval entirely right of zero means the provider's clients do worse than other SOCs." },
  superficial: { title: "Likely-superficial rate", text: "Share of closed human-handled cases the model rates as closed without real investigation (too fast, no investigation steps, templated note). Trained on prior-cycle examiner labels." },
  ppi: { title: "Prediction-powered interval (PPI++)", text: "Combines a few examiner labels with the model's score on every case. The labels correct the model's bias, so the interval stays valid even if the model is wrong, and it is narrower than labels alone." },
  wilson: { title: "Wilson interval", text: "The classical interval from the examiner's random-sample labels alone, with no help from the model. The baseline to beat." },
  trust: { title: "Data trust", text: "How far the submission itself can be relied on: completeness of records, timeliness of submission and coverage of declared assets. Low trust weakens every finding built on it." },
  capability: { title: "Capability profile", text: "Evidence of weakness across the eight SOC capability areas named in the problem statement. 0 means no evidence of weakness, 100 the strongest. Further out means weaker." },
  sources: { title: "Declared log sources", text: "The telemetry the entity says its SOC collects (EDR, firewall, DNS and so on). SAT-SA works out which ATT&CK tactics these sources can and cannot see." },
  evalue: { title: "Anytime-valid evidence (e-values)", text: "Each quarter's evidence is an e-value; their running product can be checked every quarter without inflating false alarms (e-BH). Crossing 10 means flagged at 10% FDR." },
  km: { title: "Kaplan-Meier time to close", text: "Share of high and critical cases still open after t minutes. Cases still open at the end of the period count as censored, not dropped, so slow cases are not hidden." },
  hourly: { title: "24×7 reality", text: "Median minutes to acknowledge high and critical cases for each hour of the week. A SOC that declares 24×7 monitoring should look the same at 3 am as at 3 pm." },
  regulatory: { title: "Regulatory crosswalk", text: "Maps each detector to the obligations it tests (SEBI CSCRF, CERT-In Directions 2022, RBI, CEA). “Evidence contradicts” means the records do not support the claimed practice." },
  redteamRecon: { title: "Red-team reconciliation", text: "Each technique a red team or drill executed is matched against the SOC's own alerts, cases and escalations. A technique that never alerted is a documented miss." },
  synthetic: { title: "Synthetic data", text: "From a seeded panel with a hidden answer key, so results can be checked against the truth. Every synthetic number carries this badge." },
  real: { title: "Real data: Microsoft GUIDE", text: "Real SOC incidents from thousands of organisations with analyst verdicts and expert priority labels, used to test SAT-SA outside our own simulator." },
  ledger: { title: "Audit ledger", text: "Append-only log of every submission, analysis run, sample draw and examiner decision. Each entry stores the SHA-256 hash of the one before it." },
  hash: { title: "SHA-256 hash", text: "A fingerprint of this entry plus the previous entry's hash. Changing a single byte anywhere changes every later hash, so tampering shows." },
  runHash: { title: "Analysis run", text: "Fingerprint of this analysis run and the period of records it covers. The same data and seed always give the same run hash." },
  sector: { title: "Critical sector", text: "One of the seven NCIIPC critical sectors. Entities are compared with peers of similar size and case mix across sectors." },
  mssp: { title: "Managed SOC provider (MSSP)", text: "An outside company running the SOC for one or more entities. A weak provider can quietly affect clients in several sectors at once." },
  inhouse: { title: "In-house SOC", text: "The entity runs its own SOC. In-house SOCs form part of the reference group each provider is compared against." },
  sample: { title: "Random and priority samples", text: "Random cases are drawn uniformly and are the only ones used in the estimate. Priority cases are the ones the model rates most likely superficial: they confirm weaknesses fast but never enter the estimate." },
  modelScore: { title: "Model score", text: "The model's probability that the case was handled superficially. Hidden until you record your verdict, so it cannot anchor your judgement." },
  verdict: { title: "Your verdict", text: "Superficial: the case was closed without the investigation its severity needed. Adequate: the handling was sound. Each verdict is written to the audit ledger." },
  steps: { title: "Investigation steps", text: "Number of investigation actions recorded in the case's workflow before it was closed." },
  disposition: { title: "Examiner decision", text: "Accept keeps the finding for the examination. Dismiss needs a written reason. Escalate (press and hold) raises it. Every decision is sealed in the audit ledger." },
  explain: { title: "Local AI explanation", text: "An optional plain-language summary written by a small model running offline on this machine. Every claim must quote a real record and is checked by a verifier; rejected claims are shown. Findings never depend on it." },
  records: { title: "Evidence records", text: "The exact cases, alerts or events behind this finding, straight from the entity's own submission. Click a case to see its full workflow." },
  method: { title: "Method", text: "How the detector tests this entity against its peers, and why a result this extreme would be unlikely by chance." },
  templates: { title: "Repeated note templates", text: "Analyst notes that are near-identical across many cases, a sign that notes are pasted rather than written from an investigation." },
  bunching: { title: "SLA bunching", text: "An excess of closures just under the SLA deadline against a smooth counterfactual curve: a sign that cases are closed to beat the clock, not because they are finished." },
  twin: { title: "Synthetic twin", text: "A weighted mix of peer entities that tracked this entity before the change. After the fit period, the gap between the entity and its twin is the effect." },
  decay: { title: "Rule decay", text: "Monthly alerts from detection rules that went quiet while peers' matching rules kept firing: a sign the rule was disabled or broke." },
};
